import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/ReduxProvider";

import { ToastContainer } from "react-toastify";
import "react-toastify/ReactToastify.css";
import Background from "@/components/bg/Background";

const roboto = Roboto_Condensed({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Junior Dev App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} min-h-screen black `}>
        <ReduxProvider>
          <ToastContainer limit={1} />
          <Background />
          <div className="flex-grow">{children}</div>
        </ReduxProvider>
      </body>
    </html>
  );
}
